import { NextResponse } from "next/server"

export async function GET() {
  const mockLocations = [
    {
      id: 1,
      city: "Kabankalan City",
      province: "Negros Occidental",
      barangay: "Poblacion",
      latitude: 9.9864,
      longitude: 122.8161,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 2,
      city: "Kabankalan City",
      province: "Negros Occidental",
      barangay: "Binicuil",
      latitude: 9.992,
      longitude: 122.824,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 3,
      city: "Kabankalan City",
      province: "Negros Occidental",
      barangay: "Camingawan",
      latitude: 9.975,
      longitude: 122.81,
      marker_type: "responder",
      created_at: new Date().toISOString(),
    },
    {
      id: 4,
      city: "Kabankalan City",
      province: "Negros Occidental",
      barangay: "Bantayan",
      latitude: 9.98,
      longitude: 122.82,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 5,
      city: "Ilog",
      province: "Negros Occidental",
      barangay: "Poblacion",
      latitude: 10.0472,
      longitude: 122.7453,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 6,
      city: "Cauayan",
      province: "Negros Occidental",
      barangay: "Poblacion",
      latitude: 9.9342,
      longitude: 123.1747,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 7,
      city: "Hinigaran",
      province: "Negros Occidental",
      barangay: "Poblacion",
      latitude: 10.2669,
      longitude: 122.8519,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 8,
      city: "Himamaylan",
      province: "Negros Occidental",
      barangay: "Poblacion",
      latitude: 10.1,
      longitude: 122.8667,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
    {
      id: 9,
      city: "Binalbagan",
      province: "Negros Occidental",
      barangay: "Poblacion",
      latitude: 10.1914,
      longitude: 122.8589,
      marker_type: "station",
      created_at: new Date().toISOString(),
    },
  ]

  return NextResponse.json({ locations: mockLocations })
}
